# site-1 netlify.toml
[build]
  command = "docusaurus build"
  functions = "functions"
  publish = "public"

[build.environment]
  SITE1_SPECIFIC_FLAG = "true"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
